name: "useful-tagger"
description: "A practical issue tagging program"
branding:
  icon: award
  color: green
author: 'CoolPlayLin'
inputs:
  repo-token:
    description: 'The GitHub token used to manage labels'
    required: false
    default: ${{ github.token }}
  type:
    description: 'Determine whether to tag pull_request or issue'
    required: true
  path:
    description: 'The path to the configuration file'
    required: false
    default: ""
  indeterminate-tag:
    description: 'The label used when all labels do not match'
    required: false
    default: 'triage-needed'

runs:
  using: 'node16'
  main: 'dist/index.js'